### ISSUE TITLE
Logout: does not redirect

### ISSUE THREAD

**Issue by MauricevanLeeuwen** [DAVKronos/Kronos-Website#117]
On logout the page should redirect to / (if the page can not be accessed) or reload so that all content is refreshed according to the user permissions.

**Comment by JurgenKronos** [comment]
The page should refresh to the homepage?

**Comment by MauricevanLeeuwen** [comment]
Look at: public and private routes in the React Router

**Comment by JurgenKronos** [comment]
Via javascript
