### ISSUE TITLE
Sorting fault Members with punctuation marks as first letter

### ISSUE THREAD

**Issue by JurgenKronos** [DAVKronos/Kronos-Website#131]
Our member 'Á[rest of name redacted]' can be found on the members list at the position with '*'.
Due to she has a punctuation mark as her first letter she is misplaced at the members list.

**Comment by vbosboom** [comment]
In the /app/users list this does not seem to be a problem per se. The reason she did not show up in the members list is because her name was typed in starting with a space, instead of immediately the Á.

**Comment by MauricevanLeeuwen** [comment]
Name in database is (now) corrected. Issue persists: she is now listed under "Á". Can be solved using UTF-8 normalization, see: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize
