### ISSUE TITLE
Generic form validation

### ISSUE THREAD

**Issue by rogier2012** [DAVKronos/Kronos-Website#40]
More intelligent form validation is possible. First investigate which solution fits best for our site. Starting point: [https://react-bootstrap.github.io/components/forms/#forms-validation](https://react-bootstrap.github.io/components/forms/#forms-validation)

**Comment by MauricevanLeeuwen** [comment]
RoR already validates the forms on the server-side. Validating it on the client side will be a "nice to have". Also it will be nice if validations do not require implementation on both server- and client side.

**Comment by rogier2012** [comment]
I still think you want both, since client side will give aid to the user, while server-side is protect from malicious input
